x-filebeat-common: &filebeat-common
  environment:
    ELASTICSEARCH_API_KEY: ${ELASTICSEARCH_API_KEY}
    ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS:?}
  image: elastic/filebeat:${ELK_VERSION:?}
  user: ${PUID}:${PGID}
  networks:
    - eurydice
  read_only: true
  command:
    - filebeat
    - run
    - --strict.perms=false
    - -e
    - -E
    - setup.kibana.host="http://kibana:5601"
    - output.console={pretty:true}
  healthcheck:
    test:
      - CMD
      - test
      - output
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 5s
  depends_on:
    elasticsearch:
      condition: service_healthy

services:
  filebeat-origin:
    <<: *filebeat-common
    volumes:
      - ./filebeat/filebeat.origin.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${ELASTICSEARCH_CERT_PATH:?}:/usr/share/elasticsearch/config/certs/cert.crt:ro
      - ${ORIGIN_DB_LOGS_DIR:?}:/logs/origin/postgresql:ro
      - ${PYTHON_LOGS_DIR:?}/backend-origin:/logs/origin/backend:ro
      - ${PYTHON_LOGS_DIR:?}/sender:/logs/origin/sender:ro
      - ${PYTHON_LOGS_DIR:?}/dbtrimmer-origin:/logs/origin/dbtrimmer:ro
      - ${FILEBEAT_LOGS_DIR:?}/origin:/usr/share/filebeat/logs:ro
      - ${FILEBEAT_DATA_DIR:?}/origin:/usr/share/filebeat/data

  filebeat-destination:
    <<: *filebeat-common
    volumes:
      - ./filebeat/filebeat.destination.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${ELASTICSEARCH_CERT_PATH:?}:/usr/share/elasticsearch/config/certs/cert.crt:ro
      - ${DESTINATION_DB_LOGS_DIR:?}:/logs/destination/postgresql:ro
      - ${PYTHON_LOGS_DIR:?}/backend-destination:/logs/destination/backend:ro
      - ${PYTHON_LOGS_DIR:?}/receiver:/logs/destination/receiver:ro
      - ${PYTHON_LOGS_DIR:?}/dbtrimmer-destination:/logs/destination/dbtrimmer:ro
      - ${FILEBEAT_LOGS_DIR:?}/destination:/usr/share/filebeat/logs:ro
      - ${FILEBEAT_DATA_DIR:?}/destination:/usr/share/filebeat/data

  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    networks:
      - eurydice
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - elastic:/usr/share/elasticsearch/data"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s; wait $$! || exit 1",
        ]
      interval: 5s
      timeout: 40s
      retries: 5
      start_period: 30s
    labels:
      traefik.enable: "true"
      traefik.http.routers.elasticsearch.rule: Host(`elasticsearch.localhost`)

  kibana:
    image: kibana:${ELK_VERSION}
    networks:
      - eurydice
    environment:
      SERVER_NAME: kibana.localhost
      SERVER_HOST: "0.0.0.0"
      SERVER_PUBLICBASEURL: http://kibana.localhost
      TELEMETRY_ENABLED: "false"
      ELASTICSEARCH_URL: http://${ELASTICSEARCH_HOSTS:?}
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent localhost:5601/api/status || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 45s
    labels:
      traefik.enable: "true"
      traefik.http.routers.kibana.rule: Host(`kibana.localhost`)

volumes:
  elastic:
