x-db: &db
  image: postgres:15
  networks:
    - eurydice
  environment:
    POSTGRES_DB: ${DB_NAME:?}
    POSTGRES_USER: ${DB_USER:?}
    POSTGRES_PASSWORD: ${DB_PASSWORD:?}
    TZ: "UTC"
    PGTZ: "UTC"
  user: ${PUID:?}:${PGID:?}
  read_only: true
  tmpfs:
    - /tmp:mode=770,uid=${PUID:?},gid=${PGID:?}
    - /run:mode=770,uid=${PUID:?},gid=${PGID:?}
  command:
    - "postgres"
    - "-c" # turn on json logging
    - "logging_collector=on"
    - "-c"
    - "log_destination=jsonlog"
    - "-c"
    - "log_directory=/var/log/postgresql"
    - "-c" # filebeat format
    - "log_line_prefix=%m [%p] %q%u@%d "
    - "-c" # turn on hour-based log rotation
    - "log_truncate_on_rotation=on"
    - "-c"
    - "log_filename=postgresql-%Y-%m-%d.log"
    - "-c"
    - "log_rotation_age=1d"
    - "-c"
    - "log_file_mode=0644"
    - "-c" # print statements that took more than 200ms...
    - "log_min_duration_statement=200"
    - "-c" # ...do not print other statements...
    - "log_statement=none"
    - "-c" # ...do not even print the duration of these other statements
    - "log_duration=off"
  healthcheck:
    # NOTE: DB will become healthy as soon as it has created the eurydice table
    test:
      - CMD-SHELL
      - 'psql -U ${DB_USER:?} -lqtA | grep -q "^${DB_NAME:?}|"'
    interval: 5s
    timeout: 5s
    retries: 5

services:
  ################ Common Services ################
  apache:
    build:
      context: ./apache2
      target: dev
    image: eurydice/apache:dev
    extra_hosts:
      - "dex.destination.test:127.0.0.1"
      - "dex.origin.test:127.0.0.1"
    ports:
      - 80:80
    networks:
      - eurydice

  oidc-origin:
    build:
      context: ./dex
    image: eurydice/dex:dev
    healthcheck:
      test:
        - CMD
        - nc
        - -z
        - localhost
        - "5556"
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
    environment:
      DEX_CLIENT_ID: eurydice-dev
      DEX_CLIENT_SECRET: ZXhhbXBsZS1hcHAtc2VjcmV0
      DEX_REDIRECT_URI: http://origin.test/api/v1/user/login/sso/authorize
      DEX_ISSUER: http://dex.origin.test/dex
    networks:
      - eurydice

  oidc-destination:
    build:
      context: ./dex
    image: eurydice/dex:dev
    healthcheck:
      test:
        - CMD
        - nc
        - -z
        - localhost
        - "5556"
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
    environment:
      DEX_CLIENT_ID: eurydice-dev
      DEX_CLIENT_SECRET: ZXhhbXBsZS1hcHAtc2VjcmV0
      DEX_REDIRECT_URI: http://destination.test/api/v1/user/login/sso/authorize
      DEX_ISSUER: http://dex.destination.test/dex
    networks:
      - eurydice

  openldap:
    build:
      context: ./openldap
    image: eurydice/openldap:dev
    healthcheck:
      test:
        - CMD
        - cat
        - /run/slapd/slapd.pid
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
    networks:
      - eurydice

  ################ Origin Services ################
  db-origin:
    <<: *db
    ports:
      - 5432:5432
    volumes:
      - ${ORIGIN_DB_DATA_DIR:?}:/var/lib/postgresql/data
      - ${ORIGIN_DB_LOGS_DIR:?}:/var/log/postgresql/:rw

  lidis:
    image: ${LOCAL_DOCKER_REGISTRY:-docker.io}/anssi/lidi-send:${LIDI_VERSION}
    network_mode: "host"
    environment:
      RUST_LOG: ${RUST_LOG}
    depends_on:
      lidir:
        condition: service_started
    read_only: true
    command:
      - "--from_tcp"
      - "0.0.0.0:${LIDIS_PORT}"
      - "--to_udp"
      - "0.0.0.0:${LIDIR_PORT}"
      - "--nb_clients"
      - "1"

  ################ Destination Services ################
  lidir:
    image: ${LOCAL_DOCKER_REGISTRY:-docker.io}/anssi/lidi-receive:${LIDI_VERSION}
    network_mode: "host"
    environment:
      RUST_LOG: ${RUST_LOG}
    read_only: true
    command:
      - "--from_udp"
      - "0.0.0.0:${LIDIR_PORT}"
      - "--to_tcp"
      - "0.0.0.0:7000"
      - "--nb_clients"
      - "1"

  db-destination:
    <<: *db
    ports:
      - 5433:5432
    volumes:
      - ${DESTINATION_DB_DATA_DIR:?}:/var/lib/postgresql/data
      - ${DESTINATION_DB_LOGS_DIR:?}:/var/log/postgresql/

  ################ Dev Tools ################
  pgadmin:
    image: ${LOCAL_DOCKER_REGISTRY:-docker.io}/dpage/pgadmin4:9.4.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - eurydice
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:

networks:
  eurydice:
    driver: bridge
    name: eurydice
    ipam:
      config:
        - subnet: ${EURYDICE_IPV4_SUBNET}
