# Generated by Django 5.2.5 on 2025-08-27 10:05
from pathlib import Path

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import eurydice.common.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# eurydice.origin.core.migrations.0024_maintenance


def init_maintenance(apps, schema_editor):
    Maintenance = apps.get_model("eurydice_origin_core", "Maintenance")
    Maintenance.objects.create(maintenance=False)

class Migration(migrations.Migration):

    replaces = [('eurydice_origin_core', '0001_squashed_0023_make_auto_fields_non_editable'), ('eurydice_origin_core', '0024_maintenance'), ('eurydice_origin_core', '0025_remove_outgoingtransferable_updated_at_and_more'), ('eurydice_origin_core', '0026_alter_transferablerange_byte_offset'), ('eurydice_origin_core', '0027_user_last_access'), ('eurydice_origin_core', '0028_lastpacketsentat'), ('eurydice_origin_core', '0029_remove_minio')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The priority level of the related user for transmitting files', verbose_name='Priority')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eurydice_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='OutgoingTransferable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', eurydice.common.models.fields.TransferableNameField(default='', help_text='The name of the file corresponding to the Transferable', max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('sha1', eurydice.common.models.fields.SHA1Field(default=None, help_text='The SHA-1 digest of the file corresponding to the Transferable', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='SHA-1')),
                ('size', eurydice.common.models.fields.TransferableSizeField(default=0, help_text='The size in bytes of the file corresponding to the Transferable', validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Size in bytes')),
                ('user_provided_meta', eurydice.common.models.fields.UserProvidedMetaField(default=dict, help_text='The metadata provided by the user on file submission', verbose_name='User provided metadata')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', help_text='The state of the OutgoingTransferable', max_length=7, verbose_name='State')),
                ('started_at', models.DateTimeField(help_text='A timestamp indicating the start of the transfer of the Transferable', null=True, verbose_name='Transfer start date')),
                ('finished_at', models.DateTimeField(help_text='A timestamp indicating the end of the transfer of the Transferable', null=True, verbose_name='Transfer finish date')),
                ('user_profile', models.ForeignKey(help_text='The profile of the user owning the Transferable', on_delete=django.db.models.deletion.RESTRICT, to='eurydice_origin_core.userprofile', verbose_name='User profile')),
            ],
            options={
                'db_table': 'eurydice_outgoing_transferables',
            },
        ),
        migrations.CreateModel(
            name='TransferableRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('byte_offset', models.PositiveBigIntegerField(help_text='The start position of this range in the associated Transferable', validators=[django.core.validators.MaxValueValidator(5497558138880)], verbose_name='Byte offset')),
                ('size', models.PositiveIntegerField(help_text='The size in bytes of this TransferableRange', validators=[django.core.validators.MaxValueValidator(500000000)], verbose_name='Size in bytes')),
                ('outgoing_transferable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferable_ranges', to='eurydice_origin_core.outgoingtransferable')),
            ],
            options={
                "db_table": "eurydice_transferable_ranges",
            },

        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', True), ('state', 'PENDING')), models.Q(('started_at__isnull', False), ('state__in', ('ONGOING', 'SUCCESS', 'ERROR'))), _connector='OR'), name='eurydice_origin_core_outgoingtransferable_started_at_state'),
        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state__in', ('PENDING', 'ONGOING'))), models.Q(('finished_at__isnull', False), ('state__in', ('ERROR', 'SUCCESS'))), _connector='OR'), name='eurydice_origin_core_outgoingtransferable_finished_at_state'),
        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__gte', models.F('created_at'))), name='eurydice_origin_core_outgoingtransferable_started_at_created_at'),
        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__gte', models.F('started_at'))), name='eurydice_origin_core_outgoingtransferable_finished_at_started_at'),
        ),
        migrations.CreateModel(
            name='TransferableRevocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('USER_CANCELED', 'Canceled by the user'), ('CONNECTION_LOST', 'Connection lost during user submission'), ('OBJECT_STORAGE_FULL', 'No more space on API object storage'), ('UNEXPECTED_EXCEPTION', 'Unexpected error occurred while handling Transferable')], help_text="The reason for the OutgoingTransferable's revocation", max_length=20, verbose_name='Revocation reason')),
                ('transfer_state', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('TRANSFERRED', 'Transferred'), ('ERROR', 'Error')], help_text="The reason for the OutgoingTransferable's revocation", max_length=11, verbose_name='State of the Revocation')),
            ],
            options={
                'db_table': 'eurydice_transferable_revocations',
            },
        ),
        migrations.RemoveConstraint(
            model_name='outgoingtransferable',
            name='eurydice_origin_core_outgoingtransferable_started_at_state',
        ),
        migrations.RemoveConstraint(
            model_name='outgoingtransferable',
            name='eurydice_origin_core_outgoingtransferable_finished_at_state',
        ),
        migrations.RemoveConstraint(
            model_name='outgoingtransferable',
            name='eurydice_origin_core_outgoingtransferable_started_at_created_at',
        ),
        migrations.RemoveConstraint(
            model_name='outgoingtransferable',
            name='eurydice_origin_core_outgoingtransferable_finished_at_started_at',
        ),
        migrations.RemoveField(
            model_name='outgoingtransferable',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='outgoingtransferable',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='outgoingtransferable',
            name='state',
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='submission_success',
            field=models.DateTimeField(help_text="A timestamp indicating the date at which the OutgoingTransferable's submission was successful", null=True, verbose_name="OutgoingTransferable's submission's success date"),
        ),
        migrations.AddField(
            model_name='transferablerange',
            name='finished_at',
            field=models.DateTimeField(help_text='A timestamp indicating the end of the transfer of the Transferable', null=True, verbose_name='Transfer finish date'),
        ),
        migrations.AddField(
            model_name='transferablerange',
            name='started_at',
            field=models.DateTimeField(help_text='A timestamp indicating the start of the transfer of the Transferable', null=True, verbose_name='Transfer start date'),
        ),
        migrations.AddField(
            model_name='transferablerange',
            name='transfer_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('TRANSFERRED', 'Transferred'), ('ERROR', 'Error')], default='PENDING', help_text='The state of the transfer for this OutgoingTransferable', max_length=11, verbose_name='Transfer state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', True), ('transfer_state', 'PENDING')), models.Q(('started_at__isnull', False), ('transfer_state__in', ('ONGOING', 'TRANSFERRED', 'ERROR'))), _connector='OR'), name='eurydice_origin_core_transferablerange_started_at_transfer_state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('transfer_state__in', ('PENDING', 'ONGOING'))), models.Q(('finished_at__isnull', False), ('transfer_state__in', ('ERROR', 'TRANSFERRED'))), _connector='OR'), name='eurydice_origin_core_transferablerange_finished_at_transfer_state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__gte', models.F('created_at'))), name='eurydice_origin_core_transferablerange_started_at_created_at'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__gte', models.F('started_at'))), name='eurydice_origin_core_transferablerange_finished_at_started_at'),
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='reason',
            field=models.CharField(choices=[('USER_CANCELED', 'Canceled by the user'), ('UPLOAD_SIZE_MISMATCH', 'The size of the uploaded Transferable did not match the size given in the Content-Length header.'), ('OBJECT_STORAGE_FULL', 'No more space on API object storage'), ('UNEXPECTED_EXCEPTION', 'Unexpected error occurred while handling Transferable')], help_text="The reason for the OutgoingTransferable's revocation", max_length=20, verbose_name='Revocation reason'),
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='transfer_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('TRANSFERRED', 'Transferred'), ('ERROR', 'Error')], default='PENDING', help_text="The reason for the OutgoingTransferable's revocation", max_length=11, verbose_name='State of the Revocation'),
        ),
        migrations.AddField(
            model_name='transferablerevocation',
            name='outgoing_transferable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='revocation', to='eurydice_origin_core.outgoingtransferable'),
        ),
        migrations.RemoveConstraint(
            model_name='transferablerange',
            name='eurydice_origin_core_transferablerange_started_at_transfer_state',
        ),
        migrations.RemoveConstraint(
            model_name='transferablerange',
            name='eurydice_origin_core_transferablerange_finished_at_transfer_state',
        ),
        migrations.RemoveConstraint(
            model_name='transferablerange',
            name='eurydice_origin_core_transferablerange_started_at_created_at',
        ),
        migrations.RemoveConstraint(
            model_name='transferablerange',
            name='eurydice_origin_core_transferablerange_finished_at_started_at',
        ),
        migrations.RemoveField(
            model_name='transferablerange',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='transfer_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSFERRED', 'Transferred'), ('ERROR', 'Error')], default='PENDING', help_text='The state of the transfer for this OutgoingTransferable', max_length=11, verbose_name='Transfer state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('transfer_state', 'PENDING')), models.Q(('finished_at__isnull', False), ('transfer_state__in', ('ERROR', 'TRANSFERRED'))), _connector='OR'), name='eurydice_origin_core_transferablerange_finished_at_transfer_state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__gte', models.F('created_at'))), name='eurydice_origin_core_transferablerange_finished_at_created_at'),
        ),
        migrations.AlterModelOptions(
            name='outgoingtransferable',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='outgoingtransferable',
            old_name='submission_success',
            new_name='submission_succeeded_at',
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='transfer_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSFERRED', 'Transferred'), ('ERROR', 'Error')], default='PENDING', help_text="The OutgoingTransferable's revocation state", max_length=11, verbose_name='State of the Revocation'),
        ),
        migrations.RemoveConstraint(
            model_name='transferablerange',
            name='eurydice_origin_core_transferablerange_finished_at_transfer_state',
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='transfer_state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSFERRED', 'Transferred'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='PENDING', help_text='The state of the transfer for this OutgoingTransferable', max_length=11, verbose_name='Transfer state'),
        ),
        migrations.AddConstraint(
            model_name='transferablerange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('transfer_state', 'PENDING')), models.Q(('finished_at__isnull', False), ('transfer_state__in', ('ERROR', 'TRANSFERRED', 'CANCELED'))), _connector='OR'), name='eurydice_origin_core_transferablerange_finished_at_transfer_state'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='bytes_received',
            field=eurydice.common.models.fields.TransferableSizeField(default=0, help_text='The amount of bytes received until now for the Transferable', validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Amount of bytes received'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='size',
            field=eurydice.common.models.fields.TransferableSizeField(default=None, help_text='The size in bytes of the file corresponding to the Transferable', null=True, validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Size in bytes'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sha1__isnull', True), ('submission_succeeded_at__isnull', True)), models.Q(('sha1__isnull', False), ('sha1__length', 20), ('submission_succeeded_at__isnull', False)), _connector='OR'), name='eurydice_origin_core_outgoingtransferable_sha1'),
        ),
        migrations.AddConstraint(
            model_name='outgoingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(('submission_succeeded_at__isnull', True), ('bytes_received', models.F('size')), _connector='OR'), name='eurydice_origin_core_outgoingtransferable_bytes_received'),
        ),
        migrations.AddIndex(
            model_name='transferablerange',
            index=models.Index(models.F('outgoing_transferable_id'), condition=models.Q(('transfer_state', 'PENDING')), name='eurydice_pending_ranges'),
        ),
        migrations.AddIndex(
            model_name='transferablerange',
            index=models.Index(models.F('outgoing_transferable_id'), condition=models.Q(('transfer_state', 'ERROR')), name='eurydice_error_ranges'),
        ),
        migrations.AddIndex(
            model_name='transferablerevocation',
            index=models.Index(models.F('outgoing_transferable_id'), name='eurydice_revocations_fgn_key'),
        ),
        migrations.AddIndex(
            model_name='outgoingtransferable',
            index=models.Index(fields=['-created_at'], name='eurydice_ou_created_55e483_idx'),
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='outgoing_transferable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferable_ranges', to='eurydice_origin_core.outgoingtransferable'),
        ),
        migrations.AlterField(
            model_name='transferablerevocation',
            name='outgoing_transferable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revocation', to='eurydice_origin_core.outgoingtransferable'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_bytes_transferred',
            field=eurydice.common.models.fields.TransferableSizeField(default=0, help_text="The amount of this Transferable's bytes that have already been transferred (this field is kept up-to-date via database triggers)", validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Amount of bytes transferred (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_last_range_finished_at',
            field=models.DateTimeField(help_text='A timestamp indicating the end of the transfer of the last TransferableRange associated to this Transferable (this field is kept up-to-date via database triggers)', null=True, verbose_name='Last associated range finish date (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_revocations_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRevocations associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated revocations count (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_user_revocations_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of user cancelation TransferableRevocations associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated CANCEL revocations count (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_ranges_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRanges associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated ranges (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_canceled_ranges_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRanges in CANCELED state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated CANCELED ranges (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_error_ranges_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRanges in ERROR state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated ERROR ranges (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_pending_ranges_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRanges in PENDING state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated PENDING ranges (auto-field)'),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_transferred_ranges_count',
            field=models.PositiveIntegerField(default=0, help_text='The total amount of TransferableRanges in TRANSFERRED state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated TRANSFERRED ranges (auto-field)'),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0018/initialize_auto_fields.sql"
            ).read_text("utf-8"),
            reverse_sql="",
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_range_insert.sql"
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/remove_transferable_range_insert.sql"
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_range_update.sql"
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/remove_transferable_range_update.sql"
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_revocation_insert.sql"
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/remove_transferable_revocation_insert.sql"
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_revocation_update.sql"
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/remove_transferable_revocation_update.sql"
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_auto_fields_protection.sql"
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/remove_transferable_auto_fields_protection.sql"
            ).read_text("utf-8"),
        ),
        migrations.AddField(
            model_name='outgoingtransferable',
            name='auto_state_updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='A timestamp indicating the last time the state of this Transferable changed', verbose_name='Last state update date (auto-field)'),
        ),
        migrations.AddIndex(
            model_name='outgoingtransferable',
            index=models.Index(fields=['-auto_state_updated_at'], name='eurydice_ou_auto_st_e29586_idx'),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0022/transferable_range_insert.sql",
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_range_insert.sql",
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0022/transferable_range_update.sql",
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_range_update.sql",
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0022/transferable_revocation_insert.sql",
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_revocation_insert.sql",
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0022/transferable_update.sql",
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0022/remove_transferable_update.sql",
            ).read_text("utf-8"),
        ),
        migrations.RunSQL(
            Path(
                "eurydice/origin/core/migrations/triggers/0022/transferable_auto_fields_protection.sql",
            ).read_text("utf-8"),
            reverse_sql=Path(
                "eurydice/origin/core/migrations/triggers/0019/transferable_auto_fields_protection.sql",
            ).read_text("utf-8"),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_bytes_transferred',
            field=eurydice.common.models.fields.TransferableSizeField(default=0, editable=False, help_text="The amount of this Transferable's bytes that have already been transferred (this field is kept up-to-date via database triggers)", validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Amount of bytes transferred (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_canceled_ranges_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRanges in CANCELED state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated CANCELED ranges (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_error_ranges_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRanges in ERROR state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated ERROR ranges (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_last_range_finished_at',
            field=models.DateTimeField(editable=False, help_text='A timestamp indicating the end of the transfer of the last TransferableRange associated to this Transferable (this field is kept up-to-date via database triggers)', null=True, verbose_name='Last associated range finish date (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_pending_ranges_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRanges in PENDING state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated PENDING ranges (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_ranges_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRanges associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated ranges (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_revocations_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRevocations associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated revocations count (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_transferred_ranges_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of TransferableRanges in TRANSFERRED state associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated TRANSFERRED ranges (auto-field)'),
        ),
        migrations.AlterField(
            model_name='outgoingtransferable',
            name='auto_user_revocations_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The total amount of user cancelation TransferableRevocations associated to this Transferable (this field is kept up-to-date via database triggers)', verbose_name='Associated CANCEL revocations count (auto-field)'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('maintenance', models.BooleanField(verbose_name='Whether the app is currently in maintenance mode.')),
            ],
            options={
                'db_table': 'eurydice_maintenance',
            },
        ),
        migrations.RunPython(
            code=init_maintenance,
        ),
        migrations.RemoveField(
            model_name='outgoingtransferable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transferablerange',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transferablerevocation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='transferablerange',
            name='byte_offset',
            field=models.PositiveBigIntegerField(help_text='The start position of this range in the associated Transferable', validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Byte offset'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(blank=True, help_text='Unlike last_login, this field gets updated every time the user accesses the API, even when they authenticate with an API token.', null=True, verbose_name='last access'),
        ),
        migrations.CreateModel(
            name='LastPacketSentAt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eurydice_last_packet_sent_at',
            },
        ),
    ]
