# Generated by Django 4.2.2 on 2023-06-23 15:11

import uuid

from django.db import migrations
from django.db import models


def init_maintenance(apps, schema_editor):
    Maintenance = apps.get_model("eurydice_origin_core", "Maintenance")
    Maintenance.objects.create(maintenance=False)


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_origin_core", "0001_squashed_0023_make_auto_fields_non_editable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "maintenance",
                    models.BooleanField(
                        verbose_name="Whether the app is currently in maintenance mode."
                    ),
                ),
            ],
            options={
                "db_table": "eurydice_maintenance",
            },
        ),
        migrations.RunPython(init_maintenance),
    ]
