# Generated by Django 4.2.2 on 2023-07-05 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_origin_core", "0024_maintenance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outgoingtransferable",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transferablerange",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transferablerevocation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
    ]
