# Generated by Django 4.2.4 on 2023-08-30 13:23

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eurydice_origin_core",
            "0025_remove_outgoingtransferable_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferablerange",
            name="byte_offset",
            field=models.PositiveBigIntegerField(
                help_text="The start position of this range in the associated Transferable",
                validators=[django.core.validators.MaxValueValidator(54975581388800)],
                verbose_name="Byte offset",
            ),
        ),
    ]
