# Generated by Django 4.2.18 on 2025-03-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eurydice_origin_core",
            "0028_lastpacketsentat",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferablerange",
            name="s3_bucket_name",
        ),
        migrations.RemoveField(
            model_name="transferablerange",
            name="s3_object_name",
        ),
    ]
