# Generated by Django 5.2.7 on 2025-10-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurydice_origin_core', '0001_squashed_0029_remove_minio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferablerevocation',
            name='reason',
            field=models.CharField(choices=[('USER_CANCELED', 'Canceled by the user'), ('UPLOAD_SIZE_MISMATCH', 'The size of the uploaded Transferable did not match the size given in the Content-Length header.'), ('OBJECT_STORAGE_FULL', 'No more space on API object storage'), ('UNEXPECTED_EXCEPTION', 'Unexpected error occurred while handling Transferable'), ('UPLOAD_INTERRUPTION', 'Multipart upload was interrupted')], help_text="The reason for the OutgoingTransferable's revocation", max_length=20, verbose_name='Revocation reason'),
        ),
    ]
