# Generated by Django 5.2.5 on 2025-08-27 12:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import eurydice.common.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('eurydice_destination_core', '0001_initial'), ('eurydice_destination_core', '0002_alter_user_profile_constraints'), ('eurydice_destination_core', '0003_add_incoming_transferable_fields'), ('eurydice_destination_core', '0004_update_incoming_transferable_constraints'), ('eurydice_destination_core', '0005_update_incoming_transferable_constraints'), ('eurydice_destination_core', '0006_add_incoming_transferable_rehash_intermediary'), ('eurydice_destination_core', '0007_add_s3_upload_part'), ('eurydice_destination_core', '0008_remove_incomingtransferable_s3_nb_uploaded_parts'), ('eurydice_destination_core', '0009_alter_incomingtransferable_rehash_intermediary'), ('eurydice_destination_core', '0010_alter_incomingtransferable_created_at'), ('eurydice_destination_core', '0011_added_bytes_received_to_transferables'), ('eurydice_destination_core', '0012_add_help_text_to_base_fields'), ('eurydice_destination_core', '0013_alter_incomingtransferable_created_at'), ('eurydice_destination_core', '0014_add_removed_state_to_incoming_transferable'), ('eurydice_destination_core', '0015_add_constraints'), ('eurydice_destination_core', '0016_incomingtransferable_eurydice_in_created_ac8963_idx'), ('eurydice_destination_core', '0017_alter_incomingtransferable_index_together'), ('eurydice_destination_core', '0018_alter_incomingtransferable_s3_upload_id'), ('eurydice_destination_core', '0019_remove_incomingtransferable_updated_at_and_more'), ('eurydice_destination_core', '0020_user_last_access'), ('eurydice_destination_core', '0021_lastpacketreceivedat'), ('eurydice_destination_core', '0022_remove_minio')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_user_profile_id', models.UUIDField(help_text='The UUID of the user profile on the origin side that is associated with the user profile on this side', null=True, unique=True, verbose_name='Associated user profile ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eurydice_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='IncomingTransferable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', eurydice.common.models.fields.TransferableNameField(help_text='The name of the file corresponding to the Transferable', max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('sha1', eurydice.common.models.fields.SHA1Field(help_text='The SHA-1 digest of the file corresponding to the Transferable', max_length=20, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='SHA-1')),
                ('size', eurydice.common.models.fields.TransferableSizeField(help_text='The size in bytes of the file corresponding to the Transferable', validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Size in bytes')),
                ('user_provided_meta', eurydice.common.models.fields.UserProvidedMetaField(default=dict, help_text='The metadata provided by the user on file submission', verbose_name='User provided metadata')),
                ('state', models.CharField(choices=[('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('EXPIRED', 'Expired')], default='ONGOING', help_text='The state of the IncomingTransferable', max_length=7, verbose_name='State')),
                ('finished_at', models.DateTimeField(help_text='A timestamp indicating the end of the reception of the IncomingTransferable', null=True, verbose_name='Transfer finish date')),
                ('user_profile', models.ForeignKey(help_text='The profile of the user owning the Transferable', on_delete=django.db.models.deletion.RESTRICT, to='eurydice_destination_core.userprofile', verbose_name='User profile')),
            ],
            options={
                'db_table': 'eurydice_incoming_transferables',
            },
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('associated_user_profile_id__isnull', True), ('user__isnull', True), _negated=True), name='eurydice_destination_core_userprofile_user_associated_user_profile_id'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state', 'ONGOING')), models.Q(('finished_at__isnull', False), ('state__in', ('SUCCESS', 'ERROR', 'EXPIRED'))), _connector='OR'), name='eurydice_destination_core_incomingtransferable_finished_at_state'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__gte', models.F('created_at'))), name='eurydice_destination_core_incomingtransferable_finished_at_created_at'),
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='eurydice_destination_core_userprofile_user_associated_user_profile_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='associated_user_profile_id',
            field=models.UUIDField(help_text='The UUID of the user profile on the origin side that is associated with the user profile on this side', unique=True, verbose_name='Associated user profile ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveConstraint(
            model_name='incomingtransferable',
            name='eurydice_destination_core_incomingtransferable_finished_at_state',
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='state',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ONGOING', help_text='The state of the IncomingTransferable', max_length=7, verbose_name='State'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state', 'ONGOING')), models.Q(('finished_at__isnull', False), ('state__in', ('SUCCESS', 'ERROR', 'REVOKED', 'EXPIRED'))), _connector='OR'), name='eurydice_destination_core_incomingtransferable_finished_at_state'),
        ),
        migrations.AddField(
            model_name='incomingtransferable',
            name='rehash_intermediary',
            field=models.BinaryField(default=None, help_text='Bytes corresponding to the internal state of the hashlib object as returned by eurydice.destination.utils.rehash.sha1_to_bytes', validators=[django.core.validators.MaxLengthValidator(104), django.core.validators.MinLengthValidator(104)], verbose_name='Rehash intermediary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='rehash_intermediary',
            field=models.BinaryField(default=b'\x01#Eg\x89\xab\xcd\xef\xfe\xdc\xba\x98vT2\x10\xf0\xe1\xd2\xc3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', help_text='Bytes corresponding to the internal state of the hashlib object as returned by eurydice.destination.utils.rehash.sha1_to_bytes', validators=[django.core.validators.MaxLengthValidator(104), django.core.validators.MinLengthValidator(104)], verbose_name='Rehash intermediary'),
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date'),
        ),
        migrations.AddField(
            model_name='incomingtransferable',
            name='bytes_received',
            field=eurydice.common.models.fields.TransferableSizeField(default=0, help_text='The amount of bytes received until now for the Transferable', validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Amount of bytes received'),
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='size',
            field=eurydice.common.models.fields.TransferableSizeField(default=None, help_text='The size in bytes of the file corresponding to the Transferable', null=True, validators=[django.core.validators.MaxValueValidator(54975581388800)], verbose_name='Size in bytes'),
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date'),
        ),
        migrations.RemoveConstraint(
            model_name='incomingtransferable',
            name='eurydice_destination_core_incomingtransferable_finished_at_state',
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='state',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], default='ONGOING', help_text='The state of the IncomingTransferable', max_length=7, verbose_name='State'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state', 'ONGOING')), models.Q(('finished_at__isnull', False), ('state__in', {'ERROR', 'EXPIRED', 'REMOVED', 'REVOKED', 'SUCCESS'})), _connector='OR'), name='eurydice_destination_core_incomingtransferable_finished_at_state'),
        ),
        migrations.AlterField(
            model_name='incomingtransferable',
            name='sha1',
            field=eurydice.common.models.fields.SHA1Field(default=None, help_text='The SHA-1 digest of the file corresponding to the Transferable', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='SHA-1'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'SUCCESS'), _negated=True), models.Q(('sha1__isnull', False), ('sha1__length', 20)), _connector='OR'), name='eurydice_destination_core_incomingtransferable_sha1'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(('rehash_intermediary__length', 104)), name='eurydice_destination_core_incomingtransferable_rehash_intermediary'),
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'SUCCESS'), _negated=True), ('bytes_received', models.F('size')), _connector='OR'), name='eurydice_destination_core_incomingtransferable_bytes_received'),
        ),
        migrations.AddIndex(
            model_name='incomingtransferable',
            index=models.Index(fields=['-created_at'], name='eurydice_in_created_ac8963_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingtransferable',
            index=models.Index(fields=['created_at', 'state'], name='created_at_state_idx'),
        ),
        migrations.RemoveField(
            model_name='incomingtransferable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(blank=True, help_text='Unlike last_login, this field gets updated every time the user accesses the API, even when they authenticate with an API token.', null=True, verbose_name='last access'),
        ),
        migrations.CreateModel(
            name='LastPacketReceivedAt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eurydice_last_packet_received_at',
            },
        ),
        migrations.CreateModel(
            name='FileUploadPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('part_number', models.PositiveIntegerField(help_text='The index of this part within the multipart upload.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='File multipart upload part number')),
            ],
            options={
                'db_table': 'eurydice_file_upload_part',
            },
        ),
        migrations.AddField(
            model_name='fileuploadpart',
            name='incoming_transferable',
            field=models.ForeignKey(help_text='The profile of the user owning the Transferable', on_delete=django.db.models.deletion.RESTRICT, related_name='file_upload_parts', to='eurydice_destination_core.incomingtransferable', verbose_name='Incoming Transferable'),
        ),
        migrations.AddConstraint(
            model_name='fileuploadpart',
            constraint=models.UniqueConstraint(fields=('incoming_transferable', 'part_number'), name='eurydice_destination_core_fileuploadpart_incoming_transferable_part_number'),
        ),
        migrations.AddConstraint(
            model_name='fileuploadpart',
            constraint=models.CheckConstraint(condition=models.Q(('part_number__gte', 1)), name='eurydice_destination_core_fileuploadpart_part_number'),
        ),
    ]
