# Generated by Django 3.2.3 on 2021-06-02 09:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0002_alter_user_profile_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingtransferable",
            name="s3_nb_uploaded_parts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of parts uploaded to S3 during the multipart upload identified with s3_upload_id",
                verbose_name="The number of parts uploaded to S3",
            ),
        ),
        migrations.AddField(
            model_name="incomingtransferable",
            name="s3_upload_id",
            field=models.CharField(
                default="",
                help_text="The ID for the S3 multipart upload of this IncomingTransferable.",
                max_length=89,
                verbose_name="S3 upload ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("s3_upload_id", ""),
                        ("state__in", ("SUCCESS", "ERROR", "EXPIRED")),
                    ),
                    models.Q(
                        ("state", "ONGOING"),
                        models.Q(("s3_upload_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="eurydice_destination_core_incomingtransferable_state_s3_upload_id",
            ),
        ),
    ]
