# Generated by Django 3.2.3 on 2021-06-02 14:25

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0003_add_incoming_transferable_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_finished_at_state",
        ),
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_state_s3_upload_id",
        ),
        migrations.AlterField(
            model_name="incomingtransferable",
            name="s3_upload_id",
            field=models.CharField(
                help_text="The ID for the S3 multipart upload of this IncomingTransferable.",
                max_length=89,
                validators=[django.core.validators.MinLengthValidator(89)],
                verbose_name="S3 upload ID",
            ),
        ),
        migrations.AlterField(
            model_name="incomingtransferable",
            name="state",
            field=models.CharField(
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("REVOKED", "Revoked"),
                    ("EXPIRED", "Expired"),
                ],
                default="ONGOING",
                help_text="The state of the IncomingTransferable",
                max_length=7,
                verbose_name="State",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("finished_at__isnull", True), ("state", "ONGOING")),
                    models.Q(
                        ("finished_at__isnull", False),
                        ("state__in", ("SUCCESS", "ERROR", "REVOKED", "EXPIRED")),
                    ),
                    _connector="OR",
                ),
                name="eurydice_destination_core_incomingtransferable_finished_at_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(("s3_upload_id", ""), _negated=True),
                name="eurydice_destination_core_incomingtransferable_s3_upload_id",
            ),
        ),
    ]
