# Generated by Django 3.2.3 on 2021-06-08 09:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0004_update_incoming_transferable_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_s3_bucket_name_s3_object_name",
        ),
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_s3_upload_id",
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("s3_bucket_name", ""), ("s3_object_name", ""), _negated=True
                ),
                fields=("s3_bucket_name", "s3_object_name"),
                name="eurydice_destination_core_incomingtransferable_s3_bucket_name_s3_object_name",
            ),
        ),
    ]
