# Generated by Django 3.2.3 on 2021-06-04 13:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eurydice_destination_core",
            "0006_add_incoming_transferable_rehash_intermediary",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="S3UploadPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etag",
                    models.BinaryField(
                        help_text="Bytes corresponding to the MD5 sum for the upload part. Note that S3 multipart upload parts' ETags should always be an MD5 sum. https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html",
                        max_length=16,
                        validators=[django.core.validators.MinLengthValidator(16)],
                        verbose_name="S3 multipart upload part ETag",
                    ),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(
                        help_text="The index of this part within the multipart upload.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="S3 multipart upload part number",
                    ),
                ),
                (
                    "incoming_transferable",
                    models.ForeignKey(
                        help_text="The profile of the user owning the Transferable",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="s3_upload_parts",
                        to="eurydice_destination_core.incomingtransferable",
                        verbose_name="Incoming Transferable",
                    ),
                ),
            ],
            options={
                "db_table": "eurydice_s3_upload_part",
            },
        ),
        migrations.AddConstraint(
            model_name="s3uploadpart",
            constraint=models.UniqueConstraint(
                fields=("incoming_transferable", "part_number"),
                name="eurydice_destination_core_s3uploadpart_incoming_transferable_part_number",
            ),
        ),
    ]
