# Generated by Django 3.2.3 on 2021-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "eurydice_destination_core",
            "0007_add_s3_upload_part",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomingtransferable",
            name="s3_nb_uploaded_parts",
        ),
    ]
