# Generated by Django 3.2.6 on 2021-08-26 13:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0011_added_bytes_received_to_transferables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransferable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Update date"),
        ),
        migrations.AlterField(
            model_name="s3uploadpart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Creation date"),
        ),
        migrations.AlterField(
            model_name="s3uploadpart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Update date"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Creation date"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Update date"),
        ),
    ]
