# Generated by Django 3.2.6 on 2021-08-30 16:07

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0012_add_help_text_to_base_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransferable",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Creation date"
            ),
        ),
    ]
