# Generated by Django 3.2.7 on 2021-09-14 11:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0013_alter_incomingtransferable_created_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_finished_at_state",
        ),
        migrations.AlterField(
            model_name="incomingtransferable",
            name="state",
            field=models.CharField(
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("REVOKED", "Revoked"),
                    ("EXPIRED", "Expired"),
                    ("REMOVED", "Removed"),
                ],
                default="ONGOING",
                help_text="The state of the IncomingTransferable",
                max_length=7,
                verbose_name="State",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("finished_at__isnull", True), ("state", "ONGOING")),
                    models.Q(
                        ("finished_at__isnull", False),
                        (
                            "state__in",
                            {"SUCCESS", "REVOKED", "ERROR", "REMOVED", "EXPIRED"},
                        ),
                    ),
                    _connector="OR",
                ),
                name="eurydice_destination_core_incomingtransferable_finished_at_state",
            ),
        ),
    ]
