# Generated by Django 3.2.7 on 2021-09-21 09:06

import django.core.validators
import django.db.models.expressions
from django.db import migrations
from django.db import models

import eurydice.common.models.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "eurydice_destination_core",
            "0014_add_removed_state_to_incoming_transferable",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransferable",
            name="sha1",
            field=eurydice.common.models.fields.SHA1Field(
                default=None,
                help_text="The SHA-1 digest of the file corresponding to the Transferable",
                max_length=20,
                null=True,
                validators=[django.core.validators.MinLengthValidator(20)],
                verbose_name="SHA-1",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "SUCCESS"), _negated=True),
                    models.Q(("sha1__isnull", False), ("sha1__length", 20)),
                    _connector="OR",
                ),
                name="eurydice_destination_core_incomingtransferable_sha1",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(("rehash_intermediary__length", 104)),
                name="eurydice_destination_core_incomingtransferable_rehash_intermediary",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomingtransferable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "SUCCESS"), _negated=True),
                    ("bytes_received", django.db.models.expressions.F("size")),
                    _connector="OR",
                ),
                name="eurydice_destination_core_incomingtransferable_bytes_received",
            ),
        ),
        migrations.AddConstraint(
            model_name="s3uploadpart",
            constraint=models.CheckConstraint(
                check=models.Q(("etag__length", 16)),
                name="eurydice_destination_core_s3uploadpart_etag",
            ),
        ),
        migrations.AddConstraint(
            model_name="s3uploadpart",
            constraint=models.CheckConstraint(
                check=models.Q(("part_number__gte", 1)),
                name="eurydice_destination_core_s3uploadpart_part_number",
            ),
        ),
    ]
