# Generated by Django 3.2.9 on 2021-11-15 12:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0015_add_constraints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="incomingtransferable",
            index=models.Index(
                fields=["-created_at"], name="eurydice_in_created_ac8963_idx"
            ),
        ),
    ]
