# Generated by Django 3.2.12 on 2022-11-02 12:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eurydice_destination_core",
            "0016_incomingtransferable_eurydice_in_created_ac8963_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="incomingtransferable",
            index=models.Index(
                fields=["created_at", "state"], name="created_at_state_idx"
            ),
        ),
    ]
