# Generated by Django 3.2.17 on 2023-02-08 15:30

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0017_alter_incomingtransferable_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingtransferable",
            name="s3_upload_id",
            field=models.CharField(
                help_text="The ID for the S3 multipart upload of this IncomingTransferable.",
                max_length=98,
                validators=[django.core.validators.MinLengthValidator(98)],
                verbose_name="S3 upload ID",
            ),
        ),
    ]
