# Generated by Django 4.2.2 on 2023-07-05 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eurydice_destination_core", "0018_alter_incomingtransferable_s3_upload_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomingtransferable",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="s3uploadpart",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
    ]
