# Generated by Django 4.2.20 on 2025-04-09 15:27
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("eurydice_destination_core", "0021_lastpacketreceivedat"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation date"),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(
                        help_text="The index of this part within the multipart upload.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="File multipart upload part number",
                    ),
                ),
            ],
            options={
                "db_table": "eurydice_file_upload_part",
            },
        ),
        migrations.RemoveField(
            model_name="s3uploadpart",
            name="incoming_transferable",
        ),
        migrations.RemoveConstraint(
            model_name="incomingtransferable",
            name="eurydice_destination_core_incomingtransferable_s3_bucket_name_s3_object_name",
        ),
        migrations.RemoveField(
            model_name="incomingtransferable",
            name="s3_bucket_name",
        ),
        migrations.RemoveField(
            model_name="incomingtransferable",
            name="s3_object_name",
        ),
        migrations.RemoveField(
            model_name="incomingtransferable",
            name="s3_upload_id",
        ),
        migrations.DeleteModel(
            name="S3UploadPart",
        ),
        migrations.AddField(
            model_name="fileuploadpart",
            name="incoming_transferable",
            field=models.ForeignKey(
                help_text="The profile of the user owning the Transferable",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="file_upload_parts",
                to="eurydice_destination_core.incomingtransferable",
                verbose_name="Incoming Transferable",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileuploadpart",
            constraint=models.UniqueConstraint(
                fields=("incoming_transferable", "part_number"),
                name="eurydice_destination_core_fileuploadpart_incoming_transferable_part_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileuploadpart",
            constraint=models.CheckConstraint(
                check=models.Q(("part_number__gte", 1)),
                name="eurydice_destination_core_fileuploadpart_part_number",
            ),
        ),
    ]
