# Generated by Django 5.2.5 on 2025-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurydice_destination_core', '0001_squashed_0022_remove_minio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incomingtransferable',
            name='eurydice_destination_core_incomingtransferable_finished_at_state',
        ),
        migrations.AddConstraint(
            model_name='incomingtransferable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('state', 'ONGOING')), models.Q(('finished_at__isnull', False), ('state__in', ['ERROR', 'EXPIRED', 'REVOKED', 'SUCCESS', 'REMOVED'])), _connector='OR'), name='eurydice_destination_core_incomingtransferable_finished_at_state'),
        ),
    ]
