include:
  - ../compose.dev.yml

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: devcontainer
    image: eurydice:devcontainer
    env_file: ".env.devcontainer"
    volumes:
      - "../:/home/abc/workdir/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    extra_hosts:
      - "lidis.docker.host:${LIDIS_DOCKER_HOST:-host-gateway}"
    networks:
      - eurydice
